// <auto-generated />
using System;
using AzilEdu.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzilEdu.Api.Migrations
{
    [DbContext(typeof(AzilEduDbContext))]
    [Migration("20260815123919_AddUsersAndRoles")]
    partial class AddUsersAndRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AzilEdu.Shared.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalStatusId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AnimalMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCover")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("AnimalMedia");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AnimalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnimalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dostupna za udomljenje"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rezervirana"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Udomljena"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Na liječenju"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Korisnik",
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Administrator",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Djelatnik",
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Volonter",
                            Name = "Volunteer"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Donator",
                            Name = "Donor"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DonorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonationStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DonationStatusId");

                    b.HasIndex("DonationTypeId");

                    b.HasIndex("DonorId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonationStatusId = 3,
                            DonationTypeId = 2,
                            DonorId = 1,
                            EstimatedValue = 750m,
                            ItemName = "Suha hrana za pse",
                            Notes = "Donirao 50 kg hrane",
                            Quantity = 50m
                        },
                        new
                        {
                            Id = 2,
                            DonationDate = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonationStatusId = 2,
                            DonationTypeId = 3,
                            DonorId = 2,
                            EstimatedValue = 1500m,
                            ItemName = "Kavezi i povodci",
                            Notes = "Oprema za prihvat novih životinja",
                            Quantity = 10m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 500m,
                            DonationDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonationStatusId = 2,
                            DonationTypeId = 1,
                            DonorId = 1,
                            ItemName = "",
                            Notes = "Novčana donacija za veterinara"
                        },
                        new
                        {
                            Id = 4,
                            DonationDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonationStatusId = 2,
                            DonationTypeId = 5,
                            DonorId = 4,
                            EstimatedValue = 800m,
                            ItemName = "Edukacija volontera",
                            Notes = "Udruga organizirala edukaciju"
                        },
                        new
                        {
                            Id = 5,
                            DonationDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonationStatusId = 1,
                            DonationTypeId = 2,
                            DonorId = 3,
                            EstimatedValue = 400m,
                            ItemName = "Mokra hrana za mačke",
                            Notes = "Doneseno osobno",
                            Quantity = 100m
                        },
                        new
                        {
                            Id = 6,
                            DonationDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonationStatusId = 2,
                            DonationTypeId = 3,
                            DonorId = 6,
                            EstimatedValue = 600m,
                            ItemName = "Igračke i posteljine",
                            Notes = "Sezonska donacija opreme",
                            Quantity = 20m
                        },
                        new
                        {
                            Id = 7,
                            Amount = 200m,
                            DonationDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonationStatusId = 1,
                            DonationTypeId = 1,
                            DonorId = 5,
                            ItemName = "",
                            Notes = "Prva donacija novog donatora"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Evidentirana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Potvrđena"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Iskorištena"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Otkazana"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novčana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hrana"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Oprema"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lijekovi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Usluga"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonorStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonorTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DonorStatusId");

                    b.HasIndex("DonorTypeId");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ilica 42",
                            City = "Zagreb",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorStatusId = 2,
                            DonorTypeId = 1,
                            Email = "stjepan.blazevic@gmail.com",
                            FirstName = "Stjepan",
                            LastName = "Blažević",
                            Notes = "Redoviti donator hrane",
                            OrganizationName = "",
                            Phone = "091 555 1234"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Avenija Dubrovnik 15",
                            City = "Zagreb",
                            CreatedAt = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorStatusId = 2,
                            DonorTypeId = 2,
                            Email = "donacije@zooplus.hr",
                            FirstName = "",
                            LastName = "",
                            Notes = "Donira hranu i opremu kvartalno",
                            OrganizationName = "Zooplus Hrvatska d.o.o.",
                            Phone = "01 234 5678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Vukovarska 88",
                            City = "Split",
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorStatusId = 3,
                            DonorTypeId = 1,
                            Email = "karin.simic@outlook.com",
                            FirstName = "Karin",
                            LastName = "Šimić",
                            Notes = "Donira povremeno, kontaktirati pred kampanje",
                            OrganizationName = "",
                            Phone = "095 999 4455"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tratinska 10",
                            City = "Zagreb",
                            CreatedAt = new DateTime(2024, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorStatusId = 2,
                            DonorTypeId = 3,
                            Email = "info@prijatelji-zivotinja.hr",
                            FirstName = "",
                            LastName = "",
                            Notes = "Suradnja na edukacijskim projektima",
                            OrganizationName = "Udruga Prijatelji životinja",
                            Phone = "01 987 6543"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Maksimirska 60",
                            City = "Zagreb",
                            CreatedAt = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorStatusId = 1,
                            DonorTypeId = 1,
                            Email = "boris.kralj@gmail.com",
                            FirstName = "Boris",
                            LastName = "Kralj",
                            Notes = "Novi donator, uplatio prvu donaciju",
                            OrganizationName = "",
                            Phone = "092 111 3344"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Riva 22",
                            City = "Pula",
                            CreatedAt = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorStatusId = 2,
                            DonorTypeId = 2,
                            Email = "marketing@petcenter.hr",
                            FirstName = "",
                            LastName = "",
                            Notes = "Donira opremu i igračke",
                            OrganizationName = "Petcenter d.o.o.",
                            Phone = "052 345 6789"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Korzo 5",
                            City = "Rijeka",
                            CreatedAt = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorStatusId = 4,
                            DonorTypeId = 1,
                            Email = "nikolina.djukic@yahoo.com",
                            FirstName = "Nikolina",
                            LastName = "Đukić",
                            Notes = "Prestala donirati 2024.",
                            OrganizationName = "",
                            Phone = "098 222 7788"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonorStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonorStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aktivan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Povremeni"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Neaktivan"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonorTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fizička osoba"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tvrtka"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Udruga ili organizacija"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeePositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePositionId");

                    b.HasIndex("EmployeeStatusId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "renata.stefanec@azil.hr",
                            EmployeeNumber = "AZ-001",
                            EmployeePositionId = 1,
                            EmployeeStatusId = 1,
                            FirstName = "Renata",
                            HireDate = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Štefanec",
                            Notes = "Odgovorna za smještaj i ishranu životinja",
                            Phone = "091 700 1001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivan.posavec@azil.hr",
                            EmployeeNumber = "AZ-002",
                            EmployeePositionId = 2,
                            EmployeeStatusId = 1,
                            FirstName = "Dr. Ivan",
                            HireDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Posavec",
                            Notes = "Stalni veterinar, radi pon-pet",
                            Phone = "091 700 1002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sandra.filipovic@azil.hr",
                            EmployeeNumber = "AZ-003",
                            EmployeePositionId = 3,
                            EmployeeStatusId = 1,
                            FirstName = "Sandra",
                            HireDate = new DateTime(2021, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Filipović",
                            Notes = "Koordinira raspored volontera",
                            Phone = "091 700 1003"
                        },
                        new
                        {
                            Id = 4,
                            Email = "goran.tkalcic@azil.hr",
                            EmployeeNumber = "AZ-004",
                            EmployeePositionId = 4,
                            EmployeeStatusId = 1,
                            FirstName = "Goran",
                            HireDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tkalčić",
                            Notes = "Vodi administraciju i financije",
                            Phone = "091 700 1004"
                        },
                        new
                        {
                            Id = 5,
                            Email = "mirela.vukovic@azil.hr",
                            EmployeeNumber = "AZ-005",
                            EmployeePositionId = 1,
                            EmployeeStatusId = 2,
                            FirstName = "Mirela",
                            HireDate = new DateTime(2022, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Vuković",
                            Notes = "Brine o mačkama i malim životinjama",
                            Phone = "091 700 1005"
                        },
                        new
                        {
                            Id = 6,
                            Email = "davor.knezevic@azil.hr",
                            EmployeeNumber = "AZ-006",
                            EmployeePositionId = 1,
                            EmployeeStatusId = 1,
                            FirstName = "Davor",
                            HireDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Knežević",
                            Notes = "Zamjenski djelatnik, radi na terenu",
                            Phone = "091 700 1006"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.EmployeePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmployeePositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Djelatnik azila"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Veterinar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Koordinator volontera"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.EmployeeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmployeeStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aktivan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Na dopustu ili bolovanju"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Neaktivan"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.HousingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCleanedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Occupied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HousingUnits");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteerStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerStatusId");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableFrom = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.horvat@email.com",
                            FirstName = "Ana",
                            LastName = "Horvat",
                            Notes = "Dostupna vikendom",
                            Phone = "091 234 5678",
                            Skills = "Briga o psima, šetanje",
                            VolunteerStatusId = 2
                        },
                        new
                        {
                            Id = 2,
                            AvailableFrom = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko.peric@email.com",
                            FirstName = "Marko",
                            LastName = "Perić",
                            Notes = "Fotograf volonter",
                            Phone = "098 765 4321",
                            Skills = "Fotografija životinja, društvene mreže",
                            VolunteerStatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvailableFrom = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivana.kovac@email.com",
                            FirstName = "Ivana",
                            LastName = "Kovač",
                            Notes = "Može pomagati pri veterinarskim pregledima",
                            Phone = "095 111 2233",
                            Skills = "Veterinarski tehničar",
                            VolunteerStatusId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "tomislav.babic@email.com",
                            FirstName = "Tomislav",
                            LastName = "Babić",
                            Notes = "Privremeno nedostupan zbog posla",
                            Phone = "092 444 5566",
                            Skills = "Edukacija životinja, dresura",
                            VolunteerStatusId = 3
                        },
                        new
                        {
                            Id = 5,
                            AvailableFrom = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petra.novak@email.com",
                            FirstName = "Petra",
                            LastName = "Novak",
                            Notes = "Novi volonter, u uvođenju",
                            Phone = "099 888 7766",
                            Skills = "Administracija, pisanje molbi",
                            VolunteerStatusId = 1
                        },
                        new
                        {
                            Id = 6,
                            AvailableFrom = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "luka.maric@email.com",
                            FirstName = "Luka",
                            LastName = "Marić",
                            Notes = "Može prevoziti životinje na veterinara",
                            Phone = "091 321 6549",
                            Skills = "Transport životinja, vozač",
                            VolunteerStatusId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "maja.juric@email.com",
                            FirstName = "Maja",
                            LastName = "Jurić",
                            Notes = "Završila volontiranje",
                            Phone = "098 654 3210",
                            Skills = "Šivanje, izrada igračaka za životinje",
                            VolunteerStatusId = 4
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VolunteerStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aktivan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Privremeno nedostupan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Neaktivan"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolunteerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerTaskStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerTaskTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("VolunteerTaskStatusId");

                    b.HasIndex("VolunteerTaskTypeId");

                    b.ToTable("VolunteerTasks");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VolunteerTaskStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Otvoren"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dodijeljen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "U tijeku"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Završeno"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Otkazano"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VolunteerTaskTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Šetnja"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hranjenje"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Čišćenje"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Socijalizacija"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Prijevoz"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Administracija"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Animal", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.AnimalStatus", "AnimalStatus")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnimalStatus");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AnimalMedia", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.Animal", "Animal")
                        .WithMany("Media")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AppUser", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzilEdu.Shared.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzilEdu.Shared.Models.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Donor");

                    b.Navigation("Employee");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AppUserRole", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Donation", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.DonationStatus", "DonationStatus")
                        .WithMany("Donations")
                        .HasForeignKey("DonationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.DonationType", "DonationType")
                        .WithMany("Donations")
                        .HasForeignKey("DonationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonationStatus");

                    b.Navigation("DonationType");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Donor", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.DonorStatus", "DonorStatus")
                        .WithMany("Donors")
                        .HasForeignKey("DonorStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.DonorType", "DonorType")
                        .WithMany("Donors")
                        .HasForeignKey("DonorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonorStatus");

                    b.Navigation("DonorType");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Employee", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.EmployeePosition", "EmployeePosition")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.EmployeeStatus", "EmployeeStatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeePosition");

                    b.Navigation("EmployeeStatus");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Volunteer", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.VolunteerStatus", "VolunteerStatus")
                        .WithMany("Volunteers")
                        .HasForeignKey("VolunteerStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VolunteerStatus");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTask", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzilEdu.Shared.Models.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzilEdu.Shared.Models.VolunteerTaskStatus", "VolunteerTaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("VolunteerTaskStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzilEdu.Shared.Models.VolunteerTaskType", "VolunteerTaskType")
                        .WithMany("Tasks")
                        .HasForeignKey("VolunteerTaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Volunteer");

                    b.Navigation("VolunteerTaskStatus");

                    b.Navigation("VolunteerTaskType");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Animal", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AnimalStatus", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonationStatus", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonationType", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonorStatus", b =>
                {
                    b.Navigation("Donors");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.DonorType", b =>
                {
                    b.Navigation("Donors");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.EmployeePosition", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.EmployeeStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerStatus", b =>
                {
                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTaskStatus", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.VolunteerTaskType", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
